# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yuki.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yuki.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyuki.proto\x12\x04yuki\x1a\x1cgoogle/protobuf/struct.proto\"\x99\x01\n\x08\x45nvelope\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12 \n\x07request\x18\x03 \x01(\x0b\x32\r.yuki.RequestH\x00\x12\"\n\x08response\x18\x04 \x01(\x0b\x32\x0e.yuki.ResponseH\x00\x12\x1c\n\x05\x65vent\x18\x05 \x01(\x0b\x32\x0b.yuki.EventH\x00\x42\x06\n\x04\x62ody\"X\n\x07Request\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12(\n\x07payload\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"e\n\x08Response\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\'\n\x06result\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"@\n\x05\x45vent\x12\r\n\x05topic\x18\x01 \x01(\t\x12(\n\x07payload\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Structb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yuki_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=51
  _globals['_ENVELOPE']._serialized_end=204
  _globals['_REQUEST']._serialized_start=206
  _globals['_REQUEST']._serialized_end=294
  _globals['_RESPONSE']._serialized_start=296
  _globals['_RESPONSE']._serialized_end=397
  _globals['_EVENT']._serialized_start=399
  _globals['_EVENT']._serialized_end=463
# @@protoc_insertion_point(module_scope)
